name: raining-chestnuts
volumes:
  postgres_data:
  node_modules:

networks:
  app:
  data:

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    networks:
      - app
      - data
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app

  celery:
    build:
      context: ./backend
    command: bash init_celery_workers.sh
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    networks:
      - app
      - data
    volumes:
      - ./backend:/app

  db:
    env_file:
      - ./.env
    image: postgres:17
    networks:
      - data
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - app
      - data
    ports:
      - "80:4200"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  redis:
    image: redis:7-alpine
    networks:
      - app
      - data
    ports:
      - "6379:6379"
