# Generated by Django 5.1.5 on 2025-03-31 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalPark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_temperature', models.FloatField()),
                ('mean_daily_temperature', models.FloatField()),
                ('historical_mean_temp_10', models.FloatField()),
                ('historical_mean_temp_20', models.FloatField()),
                ('historical_mean_temp_30', models.FloatField()),
                ('national_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='app.nationalpark')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
