# Generated by Django 5.1.5 on 2025-03-31 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalpark',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='weather',
            name='national_park',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='app.nationalpark'),
        ),
    ]
