# Generated by Django 5.1.5 on 2025-03-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_nationalpark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='change_10_to_20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='change_20_to_30',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='change_today_to_10',
            field=models.FloatField(null=True),
        ),
    ]
